version: '3.7'

# Services/Containers to orchestrate in this composition
services:

  # Basic PHP 5.6 & Apache2 Image Container
  php-5-6-apache:
    container_name: php-5-6-apache
    tty: true
    restart: unless-stopped
    build: 
      context: .
      target: ${APACHE_PHP56_DOCKER_BUILD_TARGET}
      dockerfile: ${DOCKER_BUILD_FILE}
      args:
        - NPM_VERSION=${NPM_VERSION}
        - APP_ENV=${APP_ENV}
      labels:
        ewc.name: "Web Server"
        ewc.description: "${APACHE_PHP56_DOCKER_BUILD_DESC}"
        ewc.php.version: "${PHP_VERSION}"
    image: ${APACHE_PHP56_DOCKER_IMAGE}:${APACHE_PHP56_DOCKER_IMAGE_TAG}
    environment:
        - NPM_VERSION=${NPM_VERSION}
        - APP_ENV=${APP_ENV}
    working_dir: /var/www
    ports:
      - ${APP_PORT}:80
      - ${APP_SSL_PORT}:443
    volumes:
      - ./public_html:/var/www/html
      - ./docker-files/php/56.local.ini:/usr/local/etc/php.ini
    networks:
      - web-app-network

# Custom network for composed containers to communicate on
networks:
  web-app-network:
    driver: bridge

