version: '3.7'

# Services/Containers to orchestrate in this composition
services:

  # Basic PHP 5.6 & Apache2 Image Container
  php-5-6-web-server:
    container_name: php-5-6-web-server
    tty: true
    restart: unless-stopped
    build: 
      context: .
      target: php-5-6-build
      dockerfile: php-5-6-apache.Dockerfile
      args:
        - NPM_VERSION=${NPM_VERSION}
        - APP_ENV=${APP_ENV}
      labels:
        ewc.name: "Web Server"
        ewc.description: "PHP & Apache Web Server"
        ewc.php.version: "5.6"
    image: $BUILD_IMAGE:$BUILD_IMAGE_TAG
    environment:
        - NPM_VERSION=${NPM_VERSION}
        - APP_ENV=${APP_ENV}
    working_dir: /var/www
    ports:
      - ${APP_PORT}:80
      - ${APP_SSL_PORT}:443
    volumes:
      - ./public_html:/var/www/html
      - ./docker-files/php/local.ini:/usr/local/etc/php.ini
    networks:
      - webapp_network

# Custom network for composed containers to communicate on
networks:
  webapp_network:
    driver: bridge

